-- MySQL Script generated by MySQL Workbench
-- Wed 11 Jan 2017 03:55:10 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema howtovideos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema howtovideos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `howtovideos` DEFAULT CHARACTER SET utf8 ;
USE `howtovideos` ;

-- -----------------------------------------------------
-- Table `howtovideos`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `howtovideos`.`table1` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
